const prompts = [
  'What is the best song for driving with the windows down on a summer day?',
  'What song reminds you of falling in love for the first time?',
  'What song would you play when you want to feel invincible?',
  'What song reminds you of your first concert?',
  'What song would make the best opener for an action movie?',
  'What song reminds you of being young?',
  'What is the best song for instilling hope?',
  'What song would make the best basis for a rock opera?',
  'What song would you play when you want to feel motivated?',
  'What is the best song for singing along when you\'re alone?',
  'What song reminds you of your first car?',
  'What is the best song for the early morning light before the world wakes up?',
  'What song reminds you of your hometown?',
  'What is the best song for wallowing when you feel sad?',
  'What song reminds you of your mom?',
  'What song would make the best opener for a comedy movie?',
  'What is the best song for belting out at karaoke?',
  'What song reminds you of your dad?',
  'What is the best song for staring at the ceiling at 3am to?',
  'What song reminds you of grandparents?',
  'What is the best song for sitting around the campfire at night?',
  'What song reminds you of childhood best friend?',
  'What song reminds you of first crush?',
  'What song would you play when you want to feel everything...all at once?',
  'What song would make the best opener for a horror movie?',
  'What song would you play when you want to feel focused?',
  'What is a song you think is being slept on?',
  'What song would you play when you want to feel sexy ;) ?',
  'What is your guilty pleasure song?',
  'What is a song you loved but hasn\'t aged well?',
  'What song would make the best opener for a romantic comedy movie?',
];

module.exports = {
  prompts
};
